name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code using shared action
      - name: Checkout code
        uses: nanjansudhakar/github_actions_library/.github/actions/checkout_action@main

      # Step 2: Set up JDK using shared action
      - name: Set up JDK 11
        uses: nanjansudhakar/github_actions_library/.github/actions/setup_jdk@main
        with:
          java-version: '11'

      # Step 3: Build the application with Maven using shared action
      - name: Build with Maven
        uses: nanjansudhakar/github_actions_library/.github/actions/build_maven@main

      # Step 4: SonarQube scan using shared action
      - name: SonarQube Scan
        uses: nanjansudhakar/github_actions_library/.github/actions/sonarqube_scan@main

      # Step 5: Checkmarx Security Scanning using shared action
      - name: Checkmarx Security Scan
        uses: nanjansudhakar/github_actions_library/.github/actions/checkmarx_scan@main
        

      # Step 6: Publish to Artifactory using shared action
      - name: Publish to Artifactory
        uses: nanjansudhakar/github_actions_library/.github/actions/publish_artifactory@main
